name: Continuous Integration

on: [push]

jobs:
  build-jar:
    strategy:
      matrix:
        os: [windows-latest]

    name: Build Effekt compiler and run tests
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Checkout Kiama fork for ScalaJS
      uses: actions/checkout@v2
      with:
        repository: b-studios/kiama
        ref: scala-js
        path: kiama

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install Kiama fork
      run: sbt publishLocal
      working-directory: kiama
