name: Continuous Integration

on: [push, pull_request]

jobs:
  build-jar:
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Build Effekt compiler and run tests
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Checkout Kiama fork for ScalaJS
      uses: actions/checkout@v2
      with:
        repository: b-studios/kiama
        ref: scala-js
        path: kiama

    - name: Checkout Kiama fork for extended LSP support
      uses: actions/checkout@v2
      with:
        repository: edding4500/kiama-effekt
        ref: extended-LSP-support
        path: kiama-effekt

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install Chez Scheme
      run: sudo apt-get install chezscheme

    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Kiama fork
      run: sbt publishLocal
      working-directory: kiama

    - name: Install Kiama fork for extended LSP support
      run: sbt publishLocal
      working-directory: kiama-effekt

    - name: Run tests
      run: sbt clean test

    - name: Assemble fully optimized js file
      run: sbt effektJS/fullOptJS
